name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers the workflow on push events to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the repository code

    - name: Set up Node.js
      uses: actions/setup-node@v2  # Set up the Node.js environment
      with:
        node-version: '16'  # Use the Node.js version compatible with your project

    - name: Install dependencies
      run: npm install  # Install project dependencies

    - name: Build project
      run: npm run build  # Build the project

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # GitHub Action for deploying to GitHub Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Token for authentication
        publish_dir: ./dist  # Directory to publish
        publish_branch: gh-pages  # Branch to deploy to (use 'gh-pages' or 'main' depending on your setup)

